services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tracklnk'
      - 'POSTGRES_PASSWORD=tracklnk'
      - 'POSTGRES_USER=tracklnk'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
