spring:

  application:
    name: tracklnk

  datasource:
    url: jdbc:postgresql://localhost:5432/tracklnk
    username: tracklnk
    password: tracklnk
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true


app:
  jwt:
    issuer: tracklnk
    access-ttl: 15m
    refresh-ttl: 7d
    rsa:
      private-key: "file:./certs/private.pem"
      public-key: "file:./certs/public.pem"

    refresh-cookie:
      name: refresh_token
      path: /api/v1/auth
      same-site: Lax   # If SPA on another domain: None (requires HTTPS)
      secure: true    # true in prod
